#!/bin/bash
user=""
pass=""
usl="mytter.org/notifications/1.1"
status="$1"
[ -z "$status" ] && while read -r aline; do
	status="$status$aline
"
done
wget -O /dev/null -i - -q --post-data "status=$status" <<< "https://${user}:${pass}@${url}/statuses/update.xml"
